### ISSUE TITLE
kp7

### ISSUE THREAD

**Issue by L0ckR** [des7ruct1on/labs_2sem#1]
kp7/vector.h

void resizeVector(vector* v, int size) {//функция изменения размера
    int* new_values = (int*)realloc(v->value, size * sizeof(int));
    v->value = new_values;
    v->size = size;
    for (int i = v->size; i < size; i++) {
        v->value[i] = 0;
    }
}

Цикл не выполнится ни разу

**Comment by des7ruct1on** [comment]
да, это по-хорошему закомментировать нужно
